micronaut:
  application:
    name: httpclient
  http:
    services:
      httpstatus:
        urls:
          - https://httpstat.us
        connect-timeout: 10s
        num-of-threads: 8
        read-timeout: 1500ms
        pool:
          enabled: true
          max-connections: 100
netty:
  default:
    allocator:
      max-order: 3
